name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: SkyNet

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Stop and Remove Existing Container
      run: |
        docker-compose down || true  # Stops and removes existing containers, but doesn’t fail if they don't exist

    - name: Remove Unused Images
      run: |
        docker image prune -af  # Cleans up old images to save space

    - name: Deploy Application
      run: |
        docker-compose up -d --build